// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateEntry(input: $models.EntryInput): $CancellablePromise<$models.Entry> {
    return $Call.ByID(992849255, input);
}

export function CreateGroup(input: $models.GroupInput): $CancellablePromise<$models.Group> {
    return $Call.ByID(1106300192, input);
}

export function DeleteEntry(id: number): $CancellablePromise<void> {
    return $Call.ByID(4288917414, id);
}

export function DeleteGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(621754065, id);
}

export function ExecuteEntry(id: number): $CancellablePromise<$models.ExecutionResult> {
    return $Call.ByID(2011178608, id);
}

export function GetState(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1375495228);
}

export function MoveEntry(id: number, targetGroupID: number): $CancellablePromise<$models.Entry> {
    return $Call.ByID(3268152092, id, targetGroupID);
}

export function ReorderEntries(groupID: number, orderedIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2916689420, groupID, orderedIDs);
}

export function ReorderGroups(orderedIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(60213948, orderedIDs);
}

export function RevealEntry(id: number): $CancellablePromise<void> {
    return $Call.ByID(4088453192, id);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2809989852);
}

export function SelectIconImage(): $CancellablePromise<string> {
    return $Call.ByID(1351070089);
}

export function SelectScript(): $CancellablePromise<string> {
    return $Call.ByID(1468992558);
}

/**
 * StopEntry terminates the running process and all child processes started by it.
 */
export function StopEntry(entryID: number): $CancellablePromise<void> {
    return $Call.ByID(521342631, entryID);
}

export function UpdateEntry(id: number, input: $models.EntryInput): $CancellablePromise<$models.Entry> {
    return $Call.ByID(2374491516, id, input);
}

export function UpdateGroup(id: number, input: $models.GroupInput): $CancellablePromise<$models.Group> {
    return $Call.ByID(2010523803, id, input);
}
