// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppState {
    "groups": Group[] | null;
    "entries": Entry[] | null;
    "settings": Setting[] | null;
}

export interface Entry {
    "id": number;
    "groupId": number;
    "name": string;
    "icon": string;
    "scriptPath": string;
    "workingDirectory": string;
    "arguments": string;
    "showTerminal": boolean;
    "sortOrder": number;
    "clickCount": number;
    "lastClickedAt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface EntryInput {
    "groupId": number;
    "name": string;
    "icon": string;
    "scriptPath": string;
    "workingDirectory": string;
    "arguments": string;
    "showTerminal": boolean;
}

export interface ExecutionEvent {
    "entryId": number;
    "entryName": string;
    "kind": string;
    "stream": string;
    "text": string;
    "status": string;
    "error": string;
    "exitCode": number;
    "timestamp": string;
    "durationMs": number;
}

export interface ExecutionResult {
    "entryId": number;
    "status": string;
    "message": string;
    "output": string;
    "error": string;
    "exitCode": number;
    "startedAt": string;
    "endedAt": string;
    "durationMs": number;
}

export interface Group {
    "id": number;
    "name": string;
    "icon": string;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface GroupInput {
    "name": string;
    "icon": string;
}

export interface Setting {
    "key": string;
    "value": string;
}
